# Generated by Django 5.0.3 on 2024-03-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_rename_recipe_message_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Recipe',
        ),
    ]
