# Generated by Django 5.0.3 on 2024-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_airesponse_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
