# Generated by Django 5.0.3 on 2024-03-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_airesponse_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
