# Generated by Django 5.0.3 on 2024-03-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_alter_airesponse_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='created',
        ),
    ]
