# Generated by Django 5.0.3 on 2024-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0007_remove_airesponse_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='ai_response',
            field=models.TextField(max_length=200),
        ),
    ]
