# Generated by Django 5.0.3 on 2024-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0008_alter_airesponse_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
